apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "codereview.fullname" . }}-data
  labels:
    {{- include "codereview.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.api.storage.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.api.storage.size }}
